// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yozdvnxbhplaahanwnoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvemR2bnhiaHBsYWFoYW53bm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTU5MDAsImV4cCI6MjA2Njc3MTkwMH0.0KUmkvyJFX47ztRdX7NetYbb3tvI71R-gqmtiJrYrjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);